name: Go Application CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.0"

      - name: Install goose CLI
        run: |
          wget https://github.com/pressly/goose/releases/download/v2.7.0/goose-linux-amd64 -O goose
          chmod +x goose
          sudo mv goose /usr/local/bin/

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Migrations
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Running migrations for Production Database"
            # Command to apply migrations to prod_your_db.sqlite
            goose -dir db/migrations sqlite3 ./my_prod_db.db up
            # You might need a custom script or tool command here
          else
            echo "Running migrations for Development Database"
            # Command to apply migrations to your_database.db
            goose -dir db/migrations sqlite3 ./your_database.db up
            # Example: migrate -path migrations -database sqlite://your_database.db up
          fi

      # Add steps for testing your application here if you have tests

      - name: Simulate Deployment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Starting application with Production Database"
            # go run . -db=my_prod_db.db
          else
            echo "Starting application with Development Database"
            # go run . -db=your_database.db
          fi
